#!/bin/bash

# C++, Go, gRPC, LLVM/Clang GitHub Repositories Star Script
# Systems Programming, Compilers, High-Performance Computing

star_repo() {
    local repo=$1
    echo -n "⭐ Starring $repo... "
    if gh api --method PUT "/user/starred/$repo" --silent 2>/dev/null; then
        echo "✓"
    else
        echo "✗ (may already be starred or doesn't exist)"
    fi
    sleep 0.3  # Be nice to GitHub API
}

echo "🚀 Starting to star C++, Go, gRPC & LLVM repositories..."
echo "============================================================"
echo ""

# LLVM/Clang Ecosystem
echo "🔧 LLVM & Clang Compiler Infrastructure..."
star_repo "llvm/llvm-project"
star_repo "llvm/circt"
star_repo "llvm/llvm-www"
star_repo "ROCm-Developer-Tools/llvm-project"
star_repo "IITH-Compilers/ml-llvm-project"
echo ""

# Top C++ Projects
echo "⚡ Top C++ Projects..."
star_repo "tensorflow/tensorflow"
star_repo "electron/electron"
star_repo "godotengine/godot"
star_repo "microsoft/terminal"
star_repo "ggml-org/llama.cpp"
star_repo "bitcoin/bitcoin"
star_repo "opencv/opencv"
star_repo "nomic-ai/gpt4all"
star_repo "tesseract-ocr/tesseract"
star_repo "protocolbuffers/protobuf"
star_repo "ocornut/imgui"
star_repo "swiftlang/swift"
star_repo "LadybirdBrowser/ladybird"
star_repo "WerWolv/ImHex"
star_repo "nlohmann/json"
star_repo "x64dbg/x64dbg"
star_repo "ggml-org/whisper.cpp"
star_repo "ClickHouse/ClickHouse"
star_repo "grpc/grpc"
star_repo "aria2/aria2"
star_repo "google/leveldb"
star_repo "facebookresearch/faiss"
star_repo "google/googletest"
star_repo "BVLC/caffe"
star_repo "aseprite/aseprite"
echo ""

# C++ Learning & Best Practices
echo "📚 C++ Learning Resources..."
star_repo "Light-City/CPlusPlusThings"
star_repo "huihut/interview"
star_repo "isocpp/CppCoreGuidelines"
star_repo "changkun/modern-cpp-tutorial"
echo ""

# Top Go Projects
echo "🐹 Top Go Projects..."
star_repo "avelino/awesome-go"
star_repo "ollama/ollama"
star_repo "golang/go"
star_repo "kubernetes/kubernetes"
star_repo "fatedier/frp"
star_repo "gin-gonic/gin"
star_repo "gohugoio/hugo"
star_repo "syncthing/syncthing"
star_repo "junegunn/fzf"
star_repo "moby/moby"
star_repo "jesseduffield/lazygit"
star_repo "caddyserver/caddy"
star_repo "nektos/act"
star_repo "prometheus/prometheus"
star_repo "minio/minio"
star_repo "traefik/traefik"
star_repo "FiloSottile/mkcert"
star_repo "rclone/rclone"
star_repo "pocketbase/pocketbase"
star_repo "wagoodman/dive"
star_repo "go-gitea/gitea"
star_repo "etcd-io/etcd"
star_repo "ethereum/go-ethereum"
star_repo "jesseduffield/lazydocker"
star_repo "gogs/gogs"
star_repo "hashicorp/terraform"
star_repo "v2ray/v2ray-core"
star_repo "usememos/memos"
echo ""

# gRPC Ecosystem
echo "🌐 gRPC & Protocol Buffers..."
star_repo "grpc/grpc-go"
star_repo "grpc/grpc-java"
star_repo "grpc/grpc-web"
star_repo "grpc/grpc-node"
star_repo "grpc/grpc-swift"
star_repo "grpc/grpc-dotnet"
star_repo "grpc-ecosystem/grpc-gateway"
star_repo "grpc-ecosystem/go-grpc-middleware"
star_repo "grpc-ecosystem/awesome-grpc"
star_repo "fullstorydev/grpcui"
star_repo "fullstorydev/grpcurl"
echo ""

# Additional Go Infrastructure
echo "🏗️ Go Infrastructure & Tools..."
star_repo "golang/tools"
star_repo "golang/protobuf"
star_repo "uber-go/zap"
star_repo "spf13/cobra"
star_repo "spf13/viper"
star_repo "stretchr/testify"
star_repo "gorilla/mux"
star_repo "labstack/echo"
star_repo "go-chi/chi"
star_repo "dgrijalva/jwt-go"
echo ""

# C++ Modern Frameworks
echo "🚀 Modern C++ Frameworks..."
star_repo "cameron314/concurrentqueue"
star_repo "google/flatbuffers"
star_repo "google/benchmark"
star_repo "abseil/abseil-cpp"
star_repo "microsoft/vcpkg"
star_repo "gabime/spdlog"
star_repo "fmtlib/fmt"
star_repo "catchorg/Catch2"
star_repo "google/re2"
star_repo "libuv/libuv"
echo ""

# Compilers & Tools
echo "🔨 Compiler Tools & Utilities..."
star_repo "WebAssembly/wabt"
star_repo "WebAssembly/binaryen"
star_repo "rui314/mold"
star_repo "llvm/llvm-test-suite"
star_repo "include-what-you-use/include-what-you-use"
echo ""

echo "============================================================"
echo "✅ Done! C++, Go, gRPC & LLVM repositories have been starred."
echo "🔗 View your stars at: https://github.com/nbajpai-code?tab=stars"
echo ""
echo "📊 Categories Covered:"
echo "   ✓ LLVM & Clang Compiler Infrastructure (5 repos)"
echo "   ✓ Top C++ Projects (25 repos)"
echo "   ✓ C++ Learning Resources (4 repos)"
echo "   ✓ Top Go Projects (28 repos)"
echo "   ✓ gRPC & Protocol Buffers (11 repos)"
echo "   ✓ Go Infrastructure & Tools (10 repos)"
echo "   ✓ Modern C++ Frameworks (10 repos)"
echo "   ✓ Compiler Tools & Utilities (5 repos)"
echo ""
echo "💡 Total: ~98 repositories"
echo ""
