#!/bin/bash

################################################################################
# arXiv Paper Tracker - Automated Setup Script
#
# This script automates the process of setting up arXiv paper tracking by:
# 1. Forking a daily arXiv tracker repository
# 2. Configuring keywords/topics
# 3. Enabling GitHub Actions
# 4. Setting up notifications
################################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
print_header() {
    echo -e "\n${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${YELLOW}ℹ${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    print_header "Checking Prerequisites"

    # Check if gh CLI is installed
    if ! command -v gh &> /dev/null; then
        print_error "GitHub CLI (gh) is not installed"
        echo "Please install it from: https://cli.github.com/"
        exit 1
    fi
    print_success "GitHub CLI is installed"

    # Check if user is authenticated
    if ! gh auth status &> /dev/null; then
        print_error "Not authenticated with GitHub CLI"
        echo "Please run: gh auth login"
        exit 1
    fi
    print_success "GitHub CLI is authenticated"

    # Check if git is installed
    if ! command -v git &> /dev/null; then
        print_error "Git is not installed"
        exit 1
    fi
    print_success "Git is installed"
}

# Display tracker options
show_tracker_options() {
    print_header "Available arXiv Trackers"

    echo "1) daily-arXiv-ai-enhanced (dw-dengwei)"
    echo "   - Auto-crawl & AI summarization"
    echo "   - Covers cs.CV, cs.GR, cs.CL, cs.AI daily"
    echo ""
    echo "2) ArxivDigest (AutoLLM)"
    echo "   - Personalized recommendations"
    echo "   - GPT-powered relevancy ratings, email digests"
    echo ""
    echo "3) DailyArXiv (MLNLP-World)"
    echo "   - Keyword-based tracking"
    echo "   - Max 100 papers per keyword, email notifications"
    echo ""
    echo "4) awesome-daily-AI-arxiv (MLNLP-World)"
    echo "   - AI/NLP/CV/Robotics digest"
    echo "   - Dynamic updates, paper navigation"
    echo ""
    echo "5) cv-arxiv-daily (Vincentqyw)"
    echo "   - Daily CV arXiv tracker"
    echo "   - Computer vision focused"
    echo ""
    echo "6) Skip - I'll set it up manually"
    echo ""
}

# Fork repository
fork_repository() {
    local repo=$1
    local repo_name=$(basename $repo)

    print_header "Forking Repository: $repo"

    # Check if already forked
    if gh repo view "$USER/$repo_name" &> /dev/null; then
        print_info "Repository already forked: $USER/$repo_name"
        read -p "Use existing fork? (y/n): " use_existing
        if [[ $use_existing != "y" ]]; then
            return 1
        fi
    else
        print_info "Forking $repo..."
        gh repo fork "$repo" --clone=false
        print_success "Repository forked successfully"
    fi

    # Clone the fork
    print_info "Cloning forked repository..."
    if [ -d "$repo_name" ]; then
        print_info "Directory already exists. Using existing directory."
        cd "$repo_name"
    else
        gh repo clone "$USER/$repo_name"
        cd "$repo_name"
    fi

    print_success "Repository cloned to: $(pwd)"
    export REPO_DIR=$(pwd)
    export REPO_NAME=$repo_name
}

# Configure keywords for different trackers
configure_daily_arxiv() {
    print_header "Configuring DailyArXiv Keywords"

    print_info "Current configuration will be backed up"

    # Backup existing config if it exists
    if [ -f "config.yaml" ]; then
        cp config.yaml config.yaml.backup
        print_success "Backed up existing config to config.yaml.backup"
    fi

    echo ""
    echo "Enter your research keywords (comma-separated):"
    echo "Examples: large language model, reinforcement learning, computer vision"
    read -p "Keywords: " keywords

    echo ""
    echo "Enter arXiv categories (comma-separated):"
    echo "Examples: cs.AI, cs.LG, cs.CL, cs.CV"
    read -p "Categories: " categories

    # Create config file
    cat > config.yaml << EOF
# DailyArXiv Configuration
# Auto-generated by setup script

keywords:
$(echo "$keywords" | tr ',' '\n' | while read keyword; do echo "  - \"${keyword// /}\""; done)

categories:
$(echo "$categories" | tr ',' '\n' | while read category; do echo "  - \"${category// /}\""; done)

max_papers_per_keyword: 100

notifications:
  email: true
  github_issues: true

update_schedule: "daily"  # daily, weekly, or cron expression
EOF

    print_success "Configuration saved to config.yaml"

    git add config.yaml
    git commit -m "Configure arXiv tracking keywords and categories" || true
}

# Configure arxiv-config.yml (for the existing tracker)
configure_arxiv_enhanced() {
    print_header "Configuring Enhanced arXiv Tracker"

    echo ""
    echo "Enter research topics/keywords (comma-separated):"
    echo "Examples: transformers, diffusion models, reinforcement learning"
    read -p "Topics: " topics

    echo ""
    echo "Enter arXiv categories (comma-separated):"
    echo "Examples: cs.AI, cs.LG, cs.CL, cs.CV"
    read -p "Categories: " categories

    # Update the config
    cat >> arxiv-config.yml << EOF

# Custom configuration added by setup script
custom_keywords:
$(echo "$topics" | tr ',' '\n' | while read topic; do echo "  - \"${topic// /}\""; done)

arxiv_categories:
$(echo "$categories" | tr ',' '\n' | while read category; do echo "  - \"${category// /}\""; done)
EOF

    print_success "Configuration updated"

    git add arxiv-config.yml
    git commit -m "Add custom arXiv tracking configuration" || true
}

# Enable GitHub Actions
enable_github_actions() {
    print_header "Enabling GitHub Actions"

    print_info "Enabling Actions for the repository..."

    # Enable Actions via API
    gh api \
        --method PUT \
        -H "Accept: application/vnd.github+json" \
        "/repos/$USER/$REPO_NAME/actions/permissions" \
        -f enabled=true \
        -f allowed_actions=all 2>/dev/null || print_info "Actions may already be enabled"

    print_success "GitHub Actions enabled"

    # Push changes to trigger first run
    print_info "Pushing configuration changes..."
    git push origin main 2>/dev/null || git push origin master 2>/dev/null || print_info "Already up to date"

    print_success "Configuration pushed to GitHub"
}

# Set up notifications
setup_notifications() {
    print_header "Setting Up Notifications"

    echo ""
    echo "How would you like to be notified of new papers?"
    echo "1) GitHub Issues (automatically created)"
    echo "2) Watch repository (GitHub notifications)"
    echo "3) Both"
    echo "4) Skip notifications"
    echo ""
    read -p "Choose option (1-4): " notif_option

    case $notif_option in
        1|3)
            print_info "GitHub Issues will be automatically created by the workflow"
            print_success "Issue notifications enabled"
            ;;
    esac

    case $notif_option in
        2|3)
            print_info "Setting up repository watch..."
            gh repo set-default "$USER/$REPO_NAME"
            gh repo watch "$USER/$REPO_NAME" --watch
            print_success "Repository watch enabled"
            ;;
    esac
}

# Add secrets if needed
setup_secrets() {
    print_header "Setting Up API Keys (Optional)"

    echo ""
    echo "Some trackers support AI summarization with API keys."
    echo "Would you like to add API keys? (y/n)"
    read -p "Add API keys: " add_keys

    if [[ $add_keys == "y" ]]; then
        echo ""
        echo "Enter OpenAI API key (or press Enter to skip):"
        read -s openai_key
        if [[ -n $openai_key ]]; then
            gh secret set OPENAI_API_KEY --body "$openai_key" --repo "$USER/$REPO_NAME"
            print_success "OpenAI API key added"
        fi

        echo ""
        echo "Enter Anthropic API key (or press Enter to skip):"
        read -s anthropic_key
        if [[ -n $anthropic_key ]]; then
            gh secret set ANTHROPIC_API_KEY --body "$anthropic_key" --repo "$USER/$REPO_NAME"
            print_success "Anthropic API key added"
        fi
    fi
}

# Main workflow
main() {
    print_header "arXiv Paper Tracker - Automated Setup"

    # Check prerequisites
    check_prerequisites

    # Get GitHub username
    USER=$(gh api user -q .login)
    print_info "GitHub username: $USER"

    # Show tracker options
    show_tracker_options
    read -p "Choose a tracker (1-6): " choice

    case $choice in
        1)
            REPO="dw-dengwei/daily-arXiv-ai-enhanced"
            CONFIG_TYPE="enhanced"
            ;;
        2)
            REPO="AutoLLM/ArxivDigest"
            CONFIG_TYPE="digest"
            ;;
        3)
            REPO="MLNLP-World/DailyArXiv"
            CONFIG_TYPE="daily"
            ;;
        4)
            REPO="MLNLP-World/awesome-daily-AI-arxiv"
            CONFIG_TYPE="awesome"
            ;;
        5)
            REPO="Vincentqyw/cv-arxiv-daily"
            CONFIG_TYPE="cv"
            ;;
        6)
            print_info "Skipping automated setup. Check the guide for manual instructions."
            exit 0
            ;;
        *)
            print_error "Invalid choice"
            exit 1
            ;;
    esac

    # Fork and clone
    fork_repository "$REPO"

    # Configure based on tracker type
    case $CONFIG_TYPE in
        daily)
            configure_daily_arxiv
            ;;
        enhanced)
            if [ -f "arxiv-config.yml" ]; then
                configure_arxiv_enhanced
            fi
            ;;
        *)
            print_info "Configuration for this tracker should be done manually"
            print_info "Please check the repository README for configuration details"
            ;;
    esac

    # Enable GitHub Actions
    enable_github_actions

    # Set up notifications
    setup_notifications

    # Set up API keys
    setup_secrets

    # Final summary
    print_header "Setup Complete!"

    echo ""
    print_success "arXiv tracker is now set up and running!"
    echo ""
    echo "📁 Repository: https://github.com/$USER/$REPO_NAME"
    echo "⚙️  Actions: https://github.com/$USER/$REPO_NAME/actions"
    echo "📊 Papers will be tracked daily"
    echo ""

    if [[ $notif_option == "1" || $notif_option == "3" ]]; then
        echo "📬 New papers will create GitHub issues automatically"
    fi

    echo ""
    print_info "Next steps:"
    echo "  1. Check the Actions tab to see the first workflow run"
    echo "  2. Review generated papers in the repository"
    echo "  3. Customize configuration as needed"
    echo "  4. Star papers you find interesting"
    echo ""

    read -p "Open repository in browser? (y/n): " open_browser
    if [[ $open_browser == "y" ]]; then
        gh repo view --web "$USER/$REPO_NAME"
    fi
}

# Run main function
main
